package com.softseve.edu.homework5;

public class TextSourceFile {

	String text = new StringBuilder()
			.append("<!DOCTYPE html>")
			.append("<html class=client-nojs lang=uk dir=ltr>")
			.append("<head>")
			.append("<meta charset=UTF-8/>")
			.append("<title>Мнемоніка — Вікіпедія</title>")
			.append("mw.user.tokens.set({editToken:+\\,patrolToken:+\\,watchToken:+\\,csrfToken:+\\});/*@nomin*/;")
			.append("});mw.loader.load([ext.cite.a11y,mediawiki.toc,mediawiki.action.view.postEdit,site,mediawiki.page.startup,mediawiki.user,mediawiki.hidpi,mediawiki.page.ready,mediawiki.legacy.wikibits,mediawiki.searchSuggest,ext.gadget.collapserefs,ext.gadget.ReferenceTooltips,ext.gadget.edittop,ext.gadget.ProtectionIndicator,ext.gadget.Statistics,ext.centralauth.centralautologin,mmv.head,mmv.bootstrap.autostart,ext.visualEditor.desktopArticleTarget.init,ext.visualEditor.targetLoader,ext.eventLogging.subscriber,ext.wikimediaEvents,ext.navigationTiming,ext.uls.eventlogger,ext.uls.init,ext.uls.compactlinks,ext.uls.interface,ext.centralNotice.geoIP,ext.centralNotice.startUp,ext.flaggedRevs.advanced,skins.vector.js]);});</script>")
			.append("<link rel=stylesheet href=/w/load.php?debug=false&amp;lang=uk&amp;modules=ext.cite.styles%7Cext.flaggedRevs.basic%7Cext.gadget.ProtectionIndicator%2CReferenceTooltips%2CshowContributorContent%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.sectionAnchor%7Cmediawiki.skinning.interface%7Cskins.vector.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector/>")
			.append("<script async= src=/w/load.php?debug=false&amp;lang=uk&amp;modules=startup&amp;only=scripts&amp;skin=vector></script>")
			.append("<meta name=ResourceLoaderDynamicStyles content=/>")
			.append("<link rel=stylesheet href=/w/load.php?debug=false&amp;lang=uk&amp;modules=site.styles&amp;only=styles&amp;skin=vector/>")
			.append("<meta name=generator content=MediaWiki 1.29.0-wmf.10/>")
			.append("<meta name=referrer content=origin-when-cross-origin/>")
			.append("<meta property=og:image content=https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Month_-_Knuckles_%28uk%29.svg/1920px-Month_-_Knuckles_%28uk%29.svg.png/>")
			.append("<link rel=alternate href=android-app://org.wikipedia/http/uk.m.wikipedia.org/wiki/%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0/>")
			.append("<link rel=alternate type=application/x-wiki title=Редагувати href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=edit/>")
			.append("<link rel=edit title=Редагувати href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=edit/>")
			.append("<link rel=apple-touch-icon href=/static/apple-touch/wikipedia.png/>")
			.append("<link rel=shortcut icon href=/static/favicon/wikipedia.ico/>")
			.append("<link rel=search type=application/opensearchdescription+xml href=/w/opensearch_desc.php title=Вікіпедія (uk)/>")
			.append("<link rel=EditURI type=application/rsd+xml href=//uk.wikipedia.org/w/api.php?action=rsd/>")
			.append("<link rel=copyright href=//creativecommons.org/licenses/by-sa/3.0//>")
			.append("<link rel=canonical href=https://uk.wikipedia.org/wiki/%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0/>")
			.append("<link rel=dns-prefetch href=//login.wikimedia.org/>")
			.append("<link rel=dns-prefetch href=//meta.wikimedia.org />")
			.append("</head>")
			.append("<body class=mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-Мнемоніка rootpage-Мнемоніка skin-vector action-view> <div id=mw-page-base class=noprint></div>")
			.append("<div id=mw-head-base class=noprint></div>")
			.append("<div id=content class=mw-body role=main>")
			.append("<a id=top></a>")
			.append("<div id=siteNotice><!-- CentralNotice --></div>")
			.append("<div class=mw-indicators>")
			.append("</div>")
			.append("<h1 id=firstHeading class=firstHeading lang=uk>Мнемоніка</h1>")
			.append("<div id=bodyContent class=mw-body-content>")
			.append("<div id=siteSub>Матеріал з Вікіпедії — вільної енциклопедії.</div>")
			.append("<div id=contentSub><div id=mw-fr-reviewnotice class=plainlinks flaggedrevs_preview><a class=external text href=//uk.wikipedia.org/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;oldid=17861380&amp;diff=cur>12 змін</a> у цій версії <a href=/wiki/%D0%92%D1%96%D0%BA%D1%96%D0%BF%D0%B5%D0%B4%D1%96%D1%8F:%D0%9F%D0%B0%D1%82%D1%80%D1%83%D0%BB%D1%8E%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F title=Вікіпедія:Патрулювання>очікують на перевірку</a>.")
			.append("<a class=external text href=//uk.wikipedia.org/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;stable=1>Стабільну версію</a> було <a class=external text href=//uk.wikipedia.org/w/index.php?title=%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%96%D1%83%D1%80%D0%BD%D0%B0%D0%BB%D0%B8&amp;type=review&amp;page=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0>перевірено</a> <i>3 квітня 2016</i>.</div><div id=mw-fr-revisiontag class=flaggedrevs_short flaggedrevs_draft_notsynced plainlinks noprint nomobile><div class=flaggedrevs_short_basic><img class=flaggedrevs-icon src=/w/extensions/FlaggedRevs/frontend/modules/img/1.png alt=На цій сторінці показано неперевірені зміни title=На цій сторінці показано неперевірені зміни /><img id=mw-fr-revisiontoggle class=fr-toggle-arrow src=/w/extensions/FlaggedRevs/frontend/modules/img/arrow-down.png style=display:none; alt=показати/приховати подробиці /></div>")
			.append("<div id=mw-fr-revisiondetails-wrapper style=position:relative;><div id=mw-fr-revisiondetails class=flaggedrevs_short_details style=display:none><a class=external text href=//uk.wikipedia.org/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;oldid=17861380&amp;diff=cur>12 змін</a> у цій версії <a href=/wiki/%D0%92%D1%96%D0%BA%D1%96%D0%BF%D0%B5%D0%B4%D1%96%D1%8F:%D0%9F%D0%B0%D1%82%D1%80%D1%83%D0%BB%D1%8E%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F title=Вікіпедія:Патрулювання>очікують на перевірку</a>.")
			.append("<a class=external text href=//uk.wikipedia.org/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;stable=1>Стабільну версію</a> було <a class=external text href=//uk.wikipedia.org/w/index.php?title=%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%96%D1%83%D1%80%D0%BD%D0%B0%D0%BB%D0%B8&amp;type=review&amp;page=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0>перевірено</a> <i>3 квітня 2016</i>.</div>")
			.append("</div>")
			.append("</div>")
			.append("</div>")
			.append("<div id=jump-to-nav class=mw-jump>")
			.append("Перейти до: <a href=#mw-head>навігація</a>, <a href=#p-search>пошук</a>")
			.append("</div>")
			.append("<div id=mw-content-text lang=uk dir=ltr class=mw-content-ltr><div class=thumb tright>")
			.append("<div class=thumbinner style=width:322px;><a href=/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:Month_-_Knuckles_(uk).svg class=image><img alt= src=//upload.wikimedia.org/wikipedia/commons/thumb/5/58/Month_-_Knuckles_%28uk%29.svg/320px-Month_-_Knuckles_%28uk%29.svg.png width=320 height=156 class=thumbimage srcset=//upload.wikimedia.org/wikipedia/commons/thumb/5/58/Month_-_Knuckles_%28uk%29.svg/480px-Month_-_Knuckles_%28uk%29.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/58/Month_-_Knuckles_%28uk%29.svg/640px-Month_-_Knuckles_%28uk%29.svg.png 2x data-file-width=450 data-file-height=220 /></a>")
			.append("<div class=thumbcaption>")
			.append("<div class=magnify><a href=/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:Month_-_Knuckles_(uk).svg class=internal title=Збільшити></a></div>")
			.append("Мнемоніка для кількості днів у місяцях року за <a href=/wiki/%D0%93%D1%80%D0%B8%D0%B3%D0%BE%D1%80%D1%96%D0%B0%D0%BD%D1%81%D1%8C%D0%BA%D0%B8%D0%B9_%D0%BA%D0%B0%D0%BB%D0%B5%D0%BD%D0%B4%D0%B0%D1%80 title=Григоріанський календар>григоріанським календарем</a> на кісточках пальців. Кожна кісточка відповідає місяцю з 31-м днем</div>")
			.append("</div>")
			.append("</div>")
			.append("<p><b>Мнемо́ніка</b> (<a href=/wiki/%D0%93%D1%80%D0%B5%D1%86%D1%8C%D0%BA%D0%B0_%D0%BC%D0%BE%D0%B2%D0%B0 title=Грецька мова>грец.</a> <span lang=el xml:lang=el><i><span style=font-family: new athena unicode, athena, gentium, code2000, palatino linotype, serif; font-size: 100%;>τα μνημονιχα</span></i></span>&#160;— мистецтво запамятовування) (<b>мнемотехніка</b>)&#160;— сукупність спеціальних прийомів і способів, що полегшують запамятовування і збільшують обсяг памяті шляхом утворення штучних асоціацій. Заміна абстрактних обєктів і фактів за допомогою понять та уявлень, які мають візуальне, аудіальне або кінестетичне представлення, обєднання обєктів з уже наявною інформацією в памяті різних типів для спрощення запамятовування.</p>")
			.append("<p>Також термін «мнемоніка» (аналог <a href=/wiki/%D0%9F%D1%96%D0%BA%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B0 title=Піктограма>піктограми</a>) вживається на позначення візуалізації (у вигляді зображення, набору символів або предметів) якогось обєкта, субєкта або явища, досить повно описує його і полегшує його запамятовування або ідентифікацію.</p>")
			.append("<p>Мнемотехніка (визначення в нових сучасних системах запамятовування)&#160;— система «внутрішнього листа», заснована для безпосереднього запису в мозок звязків між зоровими образами, що позначають значущі елементи інформації, яку запамятовуємо. Мнемонічне запамятовування складається з чотирьох етапів: кодування образів, запамятовування (зєднання двох образів), запамятовування послідовності, закріплення в памяті.</p>")
			.append("<p>Мнемотехніка застосовується для запамятовування інформації, яку складно запамятати. Наприклад, коли потрібно запамятати послідовність двохсот цифр, перелік 50-100 телефонних номерів, хронологічну таблицю, план-конспект мови, збірник анекдотів, нові іноземні слова, граматичні правила тощо. Методи мнемотехніки дозволяють абсолютно точно відтворювати послідовність інформації. Так, ряд чисел може бути відтворений мнемоністом як в прямому, так і в зворотньому порядку.</p>")
			.append("<p>Технічний арсенал сучасної мнемотехніки складається з набору уніфікованих прийомів запамятовування, що дозволяють запамятовувати різну інформацію однотипно. Основним способом запамятовування є формування асоціації.</p>")
			.append("<p>Мнемоніка дозволяє одноразово запамятовувати інформацію кожного елемента. Наприклад, 100 випадкових слів (чисел) можна запамятати послідовно з інтервалом у середньому в 6 секунд.</p>")
			.append("<p>Мнемотехніка забезпечує дуже глибоке розуміння матеріалу, оскільки методи запамятовування наказують створювати в уяві яскраві образні ілюстрації для понять і визначень.</p>")
			.append("<p></p>")
			.append("<div id=toc class=toc>")
			.append("<div id=toctitle>")
			.append("<h2>Зміст</h2>")
			.append("</div>")
			.append("<ul>")
			.append("<li class=toclevel-1 tocsection-1><a href=#.D0.86.D1.81.D1.82.D0.BE.D1.80.D1.96.D1.8F><span class=tocnumber>1</span> <span class=toctext>Історія</span></a></li>")
			.append("<li class=toclevel-1 tocsection-2><a href=#.D0.9E.D1.81.D0.BD.D0.BE.D0.B2.D0.BD.D1.96_.D0.BF.D1.80.D0.B8.D0.B9.D0.BE.D0.BC.D0.B8_.D0.BC.D0.BD.D0.B5.D0.BC.D0.BE.D0.BD.D1.96.D0.BA.D0.B8><span class=tocnumber>2</span> <span class=toctext>Основні прийоми мнемоніки</span></a>")
			.append("<ul>")
			.append("<li class=toclevel-2 tocsection-3><a href=#.D0.A0.D0.B8.D0.BC.D0.B0_.D1.82.D0.B0_.D1.80.D0.B8.D1.82.D0.BC><span class=tocnumber>2.1</span> <span class=toctext>Рима та ритм</span></a></li>")
			.append("<li class=toclevel-2 tocsection-4><a href=#.D0.9F.D1.80.D0.B8.D0.B9.D0.BE.D0.BC_.C2.AB.D0.9C.D0.B0.D1.82.D1.80.D1.8C.D0.BE.D1.88.D0.BA.D0.B0.C2.BB><span class=tocnumber>2.2</span> <span class=toctext>Прийом «Матрьошка»</span></a></li>")
			.append("<li class=toclevel-2 tocsection-5><a href=#.D0.9F.D1.80.D0.B8.D0.B9.D0.BE.D0.BC_.D1.81.D0.B8.D0.BC.D0.B2.D0.BE.D0.BB.D1.96.D0.B7.D0.B0.D1.86.D1.96.D1.97_.28.D0.BC.D0.B5.D1.82.D0.BE.D0.B4_.D0.BF.D1.96.D0.BA.D1.82.D0.BE.D0.B3.D1.80.D0.B0.D0.BC.29><span class=tocnumber>2.3</span> <span class=toctext>Прийом символізації (метод піктограм)</span></a></li>")
			.append("<li class=toclevel-2 tocsection-6><a href=#.D0.9F.D1.80.D0.B8.D0.B9.D0.BE.D0.BC_.D0.BF.D1.80.D0.B8.D0.B2.27.D1.8F.D0.B7.D0.BA.D0.B8_.D0.B4.D0.BE_.D0.B4.D0.BE.D0.B1.D1.80.D0.B5_.D0.B7.D0.BD.D0.B0.D0.B9.D0.BE.D0.BC.D0.BE.D1.97_.D1.96.D0.BD.D1.84.D0.BE.D1.80.D0.BC.D0.B0.D1.86.D1.96.D1.97.><span class=tocnumber>2.4</span> <span class=toctext>Прийом привязки до добре знайомої інформації.</span></a></li>")
			.append("</ul>")
			.append("</li>")
			.append("<li class=toclevel-1 tocsection-7><a href=#.D0.9C.D0.BD.D0.B5.D0.BC.D0.BE.D0.BD.D1.96.D1.87.D0.BD.D1.96_.D1.84.D1.80.D0.B0.D0.B7.D0.B8><span class=tocnumber>3</span> <span class=toctext>Мнемонічні фрази</span></a></li>")
			.append("<li class=toclevel-1 tocsection-8><a href=#.D0.9F.D1.80.D0.B8.D0.BC.D1.96.D1.82.D0.BA.D0.B8><span class=tocnumber>4</span> <span class=toctext>Примітки</span></a></li>")
			.append("<li class=toclevel-1 tocsection-9><a href=#.D0.94.D0.B6.D0.B5.D1.80.D0.B5.D0.BB.D0.B0><span class=tocnumber>5</span> <span class=toctext>Джерела</span></a></li>")
			.append("<li class=toclevel-1 tocsection-10><a href=#.D0.9F.D0.BE.D1.81.D0.B8.D0.BB.D0.B0.D0.BD.D0.BD.D1.8F><span class=tocnumber>6</span> <span class=toctext>Посилання</span></a></li>")
			.append("</ul>")
			.append("</div>")
			.append("<p></p>")
			.append("<h2><span class=mw-headline id=.D0.86.D1.81.D1.82.D0.BE.D1.80.D1.96.D1.8F>Історія</span><span class=mw-editsection><span class=mw-editsection-bracket>[</span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;veaction=edit&amp;section=1 class=mw-editsection-visualeditor title=Редагувати розділ: Історія>ред.</a><span class=mw-editsection-divider> • </span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=edit&amp;section=1 title=Редагувати розділ: Історія>ред. код</a><span class=mw-editsection-bracket>]</span></span></h2>")
			.append("<p>Найбільш прадавнє прото-<a href=/wiki/%D0%9A%D1%96%D0%BF%D1%83 title=Кіпу>кіпу</a> було виявлене археологом Рут Марта Шейді Соліс (Ruth Martha Shady Solís) при розкопках герметичної кімнати однієї з великих пірамід на археологічному обєкті <a href=/wiki/%D0%9D%D0%BE%D1%80%D1%82%D0%B5-%D0%A7%D1%96%D0%BA%D0%BE_(%D0%BA%D1%83%D0%BB%D1%8C%D1%82%D1%83%D1%80%D0%B0) class=mw-redirect title=Норте-Чіко (культура)>Караль</a><sup id=cite_ref-1 class=reference><a href=#cite_note-1>[1]</a></sup> (долина Супі, <a href=/wiki/%D0%9F%D0%B5%D1%80%D1%83 title=Перу>Перу</a>). За <a href=/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%82%D0%B8%D0%B3%D1%80%D0%B0%D1%84%D1%96%D1%8F title=Стратиграфія>стратиграфічним</a> шаром воно датується приблизно 3000 роком до н.&#160;е.<sup id=cite_ref-2 class=reference><a href=#cite_note-2>[2]</a></sup> і може вважатися одним із найпрадавніших (після шумерського <a href=/wiki/%D0%9A%D0%BB%D0%B8%D0%BD%D0%BE%D0%BF%D0%B8%D1%81 title=Клинопис>клинопису</a> і <a href=/wiki/%D0%84%D0%B3%D0%B8%D0%BF%D0%B5%D1%82%D1%81%D1%8C%D0%BA%D1%96_%D1%96%D1%94%D1%80%D0%BE%D0%B3%D0%BB%D1%96%D1%84%D0%B8 title=Єгипетські ієрогліфи>єгипетських ієрогліфів</a>) засобом комунікації та архівним документом людства<sup id=cite_ref-3 class=reference><a href=#cite_note-3>[3]</a></sup>. Прото-кіпу складається з 12 звисаючих ниток, деякі з яких містять вузлики, і обмотані навколо паличок.</p>")
			.append("<h2><span class=mw-headline id=.D0.9E.D1.81.D0.BD.D0.BE.D0.B2.D0.BD.D1.96_.D0.BF.D1.80.D0.B8.D0.B9.D0.BE.D0.BC.D0.B8_.D0.BC.D0.BD.D0.B5.D0.BC.D0.BE.D0.BD.D1.96.D0.BA.D0.B8>Основні прийоми мнемоніки</span><span class=mw-editsection><span class=mw-editsection-bracket>[</span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;veaction=edit&amp;section=2 class=mw-editsection-visualeditor title=Редагувати розділ: Основні прийоми мнемоніки>ред.</a><span class=mw-editsection-divider> • </span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=edit&amp;section=2 title=Редагувати розділ: Основні прийоми мнемоніки>ред. код</a><span class=mw-editsection-bracket>]</span></span></h2>")
			.append("<p>У сучасному трактуванні мнемоніка позначає всю сукупність прийомів і методів запамятовування інформації, що застосовуються в тій чи іншій системі, а термін мнемотехніка трактується як практичне застосування методів, визначених в даній конкретній мнемоніці.</p>")
			.append("<p>Основні прийоми:</p>")
			.append("<ul>")
			.append("<li>Запамятовування інформації за допомогою формування смислових фраз з початкових букв</li>")
			.append("<li>Римування</li>")
			.append("<li>Запамятовування довгих термінів або іноземних слів за допомогою співзвучних</li>")
			.append("<li>Запамятовування інформації за допомогою знаходження яскравих незвичайних асоціацій (картинки, фрази)</li>")
			.append("<li>Метод Цицерона на просторову уяву</li>")
			.append("<li>Метод Айвазовського заснований на тренуванні зорової памяті</li>")
			.append("<li>Методи запамятовування чисел:")
			.append("<ul>")
			.append("<li>закономірності</li>")
			.append("<li>знайомі числа</li>")
			.append("</ul>")
			.append("</li>")
			.append("</ul>")
			.append("<h3><span class=mw-headline id=.D0.A0.D0.B8.D0.BC.D0.B0_.D1.82.D0.B0_.D1.80.D0.B8.D1.82.D0.BC>Рима та ритм</span><span class=mw-editsection><span class=mw-editsection-bracket>[</span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;veaction=edit&amp;section=3 class=mw-editsection-visualeditor title=Редагувати розділ: Рима та ритм>ред.</a><span class=mw-editsection-divider> • </span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=edit&amp;section=3 title=Редагувати розділ: Рима та ритм>ред. код</a><span class=mw-editsection-bracket>]</span></span></h3>")
			.append("<p>Самими елементарними формами мнемоніки є ритм і рима. Ритм&#160;— це природний принцип упорядкування інформації, багато людей мимоволі застосовують його. Вони раз по раз повторюють дані із дотриманням одного і того ж ритму або одночасно підбираючи рими до них. Безсумнівно, подібним чином завчає таблиця множення або назви річок вашої країни. Самим дивним чином ритм і рима для запамятовування були використані в усних культурних традиції країн, на той момент не володіли писемністю, наприклад у гомерівській епопеї. Однак потрібно звернути увагу на те, що запамятовування з використанням ритму і рими не гарантує розуміння інформації, забезпечується тільки її запамятовування.</p>")
			.append("<p>Найчастіше педагоги пропонують використовувати школярам римовані підказки. Наприклад,1-блондин, 2- вдова… Цей метод називають методом асоціацій.</p>")
			.append("<p>Наприклад, послідовність кольорів веселки школярі нерідко запамятовують за допомогою фрази «Чепурний пузатий жук зїв барвистий свіжий фрукт», де початкові літери слів кодують назви кольорів.</p>")
			.append("<h3><span class=mw-headline id=.D0.9F.D1.80.D0.B8.D0.B9.D0.BE.D0.BC_.C2.AB.D0.9C.D0.B0.D1.82.D1.80.D1.8C.D0.BE.D1.88.D0.BA.D0.B0.C2.BB>Прийом «Матрьошка»</span><span class=mw-editsection><span class=mw-editsection-bracket>[</span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;veaction=edit&amp;section=4 class=mw-editsection-visualeditor title=Редагувати розділ: Прийом «Матрьошка»>ред.</a><span class=mw-editsection-divider> • </span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=edit&amp;section=4 title=Редагувати розділ: Прийом «Матрьошка»>ред. код</a><span class=mw-editsection-bracket>]</span></span></h3>")
			.append("<p>Образи зєднуються парами. Перший образ асоціації завжди значніший другого і містить у собі другий. Після зєднання першого і другого способу треба перевести свою увагу на другий образ (перший повинен зникнути зі свідомості). Подумки збільшити другий образ і створюйте асоціацію між другим і третім образами. І так далі. Образи постійно вкладаються один в одного. При цьому в асоціації завжди повинні бути чітко видно тільки два образи. Пригадування здійснюється аналогічно. Треба уявити перший образ і чекати, коли з памяті виникне другий. Потім треба переключити увагу на другий, збільшивши його, і чекати появи третього і т.д. Приклад. Земля - Океанія - Тихий океан – Філіппінське море</p>")
			.append("<h3><span class=mw-headline id=.D0.9F.D1.80.D0.B8.D0.B9.D0.BE.D0.BC_.D1.81.D0.B8.D0.BC.D0.B2.D0.BE.D0.BB.D1.96.D0.B7.D0.B0.D1.86.D1.96.D1.97_.28.D0.BC.D0.B5.D1.82.D0.BE.D0.B4_.D0.BF.D1.96.D0.BA.D1.82.D0.BE.D0.B3.D1.80.D0.B0.D0.BC.29>Прийом символізації (метод піктограм)</span><span class=mw-editsection><span class=mw-editsection-bracket>[</span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;veaction=edit&amp;section=5 class=mw-editsection-visualeditor title=Редагувати розділ: Прийом символізації (метод піктограм)>ред.</a><span class=mw-editsection-divider> • </span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=edit&amp;section=5 title=Редагувати розділ: Прийом символізації (метод піктограм)>ред. код</a><span class=mw-editsection-bracket>]</span></span></h3>")
			.append("<p>Прийом символізації застосовується для запамятовування абстрактних понять, що не мають чіткого образного значення. Одне й те ж слово може бути по-різному закодоване в образи різними людьми. Але, як правило, вдається використовувати для кодування різноманітні символи, добре закріплені у свідомості більшості людей. Символи оточують нас з усіх боків. Перекладаючи дорожні знаки у зміст, ми займаємося з мнемотехнікою. Легенда карти, умовні позначки, олімпійські піктограми символізують різні види спорту; всім добре знайомі символи миру («Білий голуб»), смерті («Череп»), повільності («Черепаха»), влади («Корона») та багато інших. Приклади кодування слів в образи прийомом символізації: холод «Лід», Гудзонова затока «ґудзик», Антарктида «пінгвіни», Африка «пустеля Сахара», Антарктида «Королева холоду», вічність «Піраміди», нескінченність «Математичний знак безкінечності»</p>")
			.append("<h3><span class=mw-headline id=.D0.9F.D1.80.D0.B8.D0.B9.D0.BE.D0.BC_.D0.BF.D1.80.D0.B8.D0.B2.27.D1.8F.D0.B7.D0.BA.D0.B8_.D0.B4.D0.BE_.D0.B4.D0.BE.D0.B1.D1.80.D0.B5_.D0.B7.D0.BD.D0.B0.D0.B9.D0.BE.D0.BC.D0.BE.D1.97_.D1.96.D0.BD.D1.84.D0.BE.D1.80.D0.BC.D0.B0.D1.86.D1.96.D1.97.>Прийом привязки до добре знайомої інформації.</span><span class=mw-editsection><span class=mw-editsection-bracket>[</span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;veaction=edit&amp;section=6 class=mw-editsection-visualeditor title=Редагувати розділ: Прийом привязки до добре знайомої інформації.>ред.</a><span class=mw-editsection-divider> • </span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=edit&amp;section=6 title=Редагувати розділ: Прийом привязки до добре знайомої інформації.>ред. код</a><span class=mw-editsection-bracket>]</span></span></h3>")
			.append("<p>Що значить добре знайома інформація? Це - інформація, яка знаходиться у памяті. Нові запамятовуються відомості можуть складатися з елементів добре знайомої інформації. Прикладами добре знайомої інформації можуть бути дати: 1917 рік, 1941, 1812 і 1861 рр. Власне імя і назву вулиці, на якій мешкає особа, телефонний номер, і напис SONY на телевізорі. Приклади кодування слів в образи прийомом привязки до добре знайомої інформації: штат Вашингтон – «Долар», планета Марс - шоколадка «Марс», планета Венера – «Статуя Венери», прізвище Блек – образ «Чорний квадрат»</p>")
			.append("<h2><span class=mw-headline id=.D0.9C.D0.BD.D0.B5.D0.BC.D0.BE.D0.BD.D1.96.D1.87.D0.BD.D1.96_.D1.84.D1.80.D0.B0.D0.B7.D0.B8>Мнемонічні фрази</span><span class=mw-editsection><span class=mw-editsection-bracket>[</span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;veaction=edit&amp;section=7 class=mw-editsection-visualeditor title=Редагувати розділ: Мнемонічні фрази>ред.</a><span class=mw-editsection-divider> • </span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=edit&amp;section=7 title=Редагувати розділ: Мнемонічні фрази>ред. код</a><span class=mw-editsection-bracket>]</span></span></h2>")
			.append("<p>Відомі такі українські мнемонічні фрази:</p>")
			.append("<table border=1>")
			.append("<tr align=center>")
			.append("<td width=45%><b>Фраза</b></td>")
			.append("<td><b>Область застосування</b></td>")
			.append("</tr>")
			.append("<tr>")
			.append("<td>Народив Роман Дитину, Зрубав Очеретину, Мячик Кинув</td>")
			.append("<td>Для запамятовування порядку відмінків української мови&#160;— Називний, Родовий, Давальний, Знахідний, Орудний, Місцевий, Кличний</td>")
			.append("</tr>")
			.append("<tr>")
			.append("<td>Маючи Великі Здібності Маленький Юрко Співав Українські Народні Пісні<br />")
			.append("Маленький Василько З Маленьким Юрком Співали Українські Народні Пісні</td>")
			.append("<td>Для запамятовування порядку планет Сонячної системи&#160;— Меркурія, Венери, Землі, Марса, Юпітера, Сатурна, Урана, Нептуна, Плутона</td>")
			.append("</tr>")
			.append("<tr>")
			.append("<td>")
			.append("<p>Чоловік Охоче Жінку Заміж Бере Собі Файну <i><a rel=nofollow class=external autonumber href=http://ukrlife.org/main/uacrim/vitiuk.html>[1]</a></i>.<br />")
			.append("Чому Олені Живуть Зимою Без Своїх Фантазій?<br />")
			.append("Чарівна Осінь&#160;— Життя Знову Бє Сивий Фарфор <i><a rel=nofollow class=external autonumber href=http://community.livejournal.com/ua_mova/302599.html>[2]</a></i>.<br />")
			.append("Чарка Оковитої Живо Знуртує Байдуже Серце Флегматика.<br />")
			.append("Чом Овес Жують Зайці? Бо Старанні Фахівці.<br />")
			.append("Чи Омелько жити зможе без своїх фантазій?<br />")
			.append("Через Огорожу Жовто-Зелені Банани Снуться Фантастично.<br />")
			.append("Чи Одхилить Жінка Зранку Бісову Свою Фіранку?<br />")
			.append("Чапля Осінь Жде Завзято, Буде Сани Фарбувати.</p>")
			.append("<p>Чепурний Пузатий Жук Зїв Барвистий Свіжий Фрукт</p>")
			.append("</td>")
			.append("<td>Для запамятовування сімох кольорів сонячного спектра&#160;— червоного, оранжевого, жовтого, зеленого, блакитного, синього, фіолетового</td>")
			.append("</tr>")
			.append("<tr>")
			.append("<td>Де Ти ЗїСи Ці ЛиНи?</td>")
			.append("<td>Для запамятовування приголосних, після яких пишеться мякий знак</td>")
			.append("</tr>")
			.append("<tr>")
			.append("<td>МаВПа БуФ.</td>")
			.append("<td>Для запамятовування приголосних, після яких пишеться апостроф</td>")
			.append("</tr>")
			.append("<tr>")
			.append("<td>Де Ти ЗїСи Цю ЧаШу ЖиРу.</td>")
			.append("<td>Для запамятовування приголосних, після яких в словах іншомовного походження пишеться «И» (<a href=/wiki/%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%BE_%D0%B4%D0%B5%D0%B2%27%D1%8F%D1%82%D0%BA%D0%B8 title=Правило девятки>Правило девятки</a>)</td>")
			.append("</tr>")
			.append("<tr>")
			.append("<td>Кафе «Птах».<br />")
			.append("КоПиТиФХа&#160;— зла чаклунка Копитифха, яка перетворює префікси.")
			.append("<p>Коля приніс хворій Тетянці фрукти.</p>")
			.append("</td>")
			.append("<td>Для запамятовування приголосних, перед якими префікс «з-» перетворюється на «с-»</td>")
			.append("</tr>")
			.append("</table>")
			.append("<h2><span class=mw-headline id=.D0.9F.D1.80.D0.B8.D0.BC.D1.96.D1.82.D0.BA.D0.B8>Примітки</span><span class=mw-editsection><span class=mw-editsection-bracket>[</span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;veaction=edit&amp;section=8 class=mw-editsection-visualeditor title=Редагувати розділ: Примітки>ред.</a><span class=mw-editsection-divider> • </span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=edit&amp;section=8 title=Редагувати розділ: Примітки>ред. код</a><span class=mw-editsection-bracket>]</span></span></h2>")
			.append("<div class=reflist style=list-style-type: decimal;>")
			.append("<ol class=references>")
			.append("<li id=cite_note-1><span class=mw-cite-backlink><a href=#cite_ref-1>↑</a></span> <span class=reference-text><span class=citation web>Shady Solís, Ruth Martha. <a rel=nofollow class=external text href=http://www.webcitation.org/611ui626v>La ciudad sagrada de Caral-Supe en los albores de la civilización en el Perú</a>. Архів <a rel=nofollow class=external text href=http://sisbib.unmsm.edu.pe/Bibvirtual/Libros/Arqueologia/ciudad_sagrada/indice.htm>оригіналу</a> за 2011-08-18.</span><span title=ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fuk.wikipedia.org%3A%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;rft.aulast=Shady+Sol%C3%ADs%2C+Ruth+Martha.&amp;rft.au=Shady+Sol%C3%ADs%2C+Ruth+Martha.&amp;rft.btitle=La+ciudad+sagrada+de+Caral-Supe+en+los+albores+de+la+civilizaci%C3%B3n+en+el+Per%C3%BA&amp;rft.genre=book&amp;rft_id=http%3A%2F%2Fsisbib.unmsm.edu.pe%2FBibvirtual%2FLibros%2FArqueologia%2Fciudad_sagrada%2Findice.htm&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook class=Z3988><span style=display:none;>&#160;</span></span></span></li>")
			.append("<li id=cite_note-2><span class=mw-cite-backlink><a href=#cite_ref-2>↑</a></span> <span class=reference-text><span class=citation web><a rel=nofollow class=external text href=http://www.webcitation.org/611uia6Dl>Perú. Descubren quipu con más de 4500 años de antigüedad en Caral</a>. Архів <a rel=nofollow class=external text href=http://terraeantiqvae.blogia.com/2005/071602-peru.-descubren-quipu-con-mas-de-4500-anos-de-antiguedad-en-caral.php>оригіналу</a> за 2011-08-18.</span><span title=ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fuk.wikipedia.org%3A%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;rft.btitle=Per%C3%BA.+Descubren+quipu+con+m%C3%A1s+de+4500+a%C3%B1os+de+antig%C3%BCedad+en+Caral&amp;rft.genre=book&amp;rft_id=http%3A%2F%2Fterraeantiqvae.blogia.com%2F2005%2F071602-peru.-descubren-quipu-con-mas-de-4500-anos-de-antiguedad-en-caral.php&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook class=Z3988><span style=display:none;>&#160;</span></span></span></li>")
			.append("<li id=cite_note-3><span class=mw-cite-backlink><a href=#cite_ref-3>↑</a></span> <span class=reference-text><span class=citation web><a rel=nofollow class=external text href=http://www.webcitation.org/611ukdheC>Unraveling Khipu’s Secrets</a>. Архів <a rel=nofollow class=external text href=http://www.charlesmann.org/articles/Science-khipu-decipher-08-05.pdf>оригіналу</a> за 2011-08-18.</span><span title=ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fuk.wikipedia.org%3A%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;rft.btitle=Unraveling+Khipu%E2%80%99s+Secrets&amp;rft.genre=book&amp;rft_id=http%3A%2F%2Fwww.charlesmann.org%2Farticles%2FScience-khipu-decipher-08-05.pdf&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook class=Z3988><span style=display:none;>&#160;</span></span></span></li>")
			.append("</ol>")
			.append("</div>")
			.append("<h2><span class=mw-headline id=.D0.94.D0.B6.D0.B5.D1.80.D0.B5.D0.BB.D0.B0>Джерела</span><span class=mw-editsection><span class=mw-editsection-bracket>[</span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;veaction=edit&amp;section=9 class=mw-editsection-visualeditor title=Редагувати розділ: Джерела>ред.</a><span class=mw-editsection-divider> • </span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=edit&amp;section=9 title=Редагувати розділ: Джерела>ред. код</a><span class=mw-editsection-bracket>]</span></span></h2>")
			.append("<ul>")
			.append("<li><a rel=nofollow class=external text href=http://community.livejournal.com/ua_mova/282370.html>Запитання в спільноті ua_mova</a></li>")
			.append("</ul>")
			.append("<h2><span class=mw-headline id=.D0.9F.D0.BE.D1.81.D0.B8.D0.BB.D0.B0.D0.BD.D0.BD.D1.8F>Посилання</span><span class=mw-editsection><span class=mw-editsection-bracket>[</span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;veaction=edit&amp;section=10 class=mw-editsection-visualeditor title=Редагувати розділ: Посилання>ред.</a><span class=mw-editsection-divider> • </span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=edit&amp;section=10 title=Редагувати розділ: Посилання>ред. код</a><span class=mw-editsection-bracket>]</span></span></h2>")
			.append("<ul>")
			.append("<li><a rel=nofollow class=external text href=http://www.mova.info/Page2.aspx?l1=145>В. Хромов Мнемотехніка&#160;— Мистецтво запамятовування</a></li>")
			.append("<li><a rel=nofollow class=external text href=http://ariom.ru/litera-dop.html>М. Зиганов, В. Козаренко «Мнемотехника: Запоминание на основе визуального мышления»</a></li>")
			.append("<li><a rel=nofollow class=external text href=http://www.mnemonica.ru/>Мнемоника&#160;— розвиток памяті в мережі</a></li>")
			.append("<li><a rel=nofollow class=external text href=http://mnemonics.pp.ua/>Мнемоніка крок за кроком (україномовний ресурс)</a></li>")
			.append("</ul>")
			.append("<!-- ")
			.append("NewPP limit report")
			.append("Parsed by mw1239")
			.append("Cached time: 20170118051120")
			.append("Cache expiry: 2592000")
			.append("Dynamic content: false")
			.append("CPU time usage: 0.036 seconds")
			.append("Real time usage: 0.051 seconds")
			.append("Preprocessor visited node count: 184/1000000")
			.append("Preprocessor generated node count: 0/1500000")
			.append("Post‐expand include size: 5199/2097152 bytes")
			.append("Template argument size: 195/2097152 bytes")
			.append("Highest expansion depth: 6/40")
			.append("Expensive parser function count: 0/500")
			.append("Lua time usage: 0.008/10.000 seconds")
			.append("Lua memory usage: 988 KB/50 MB")
			.append("-->")
			.append("<!-- ")
			.append("Transclusion expansion time report (%,ms,calls,template)")
			.append("100.00% 33.181 1 - -total")
			.append("84.42% 28.010 1 - Шаблон:Reflist")
			.append("67.69% 22.461 3 - Шаблон:Cite_web")
			.append("8.71% 2.891 1 - Шаблон:Lang-el")
			.append("6.00% 1.991 1 - Шаблон:Lang-el2")
			.append("2.84% 0.942 1 - Шаблон:Lang")
			.append("-->")
			.append("<!-- Saved in parser cache with key ukwiki:pcache:idhash:47562-0!*!0!!uk!4!* and timestamp 20170118051120 and revision id 18645633")
			.append("-->")
			.append("Отримано з <a dir=ltr href=https://uk.wikipedia.org/w/index.php?title=Мнемоніка&amp;oldid=18645633>https://uk.wikipedia.org/w/index.php?title=Мнемоніка&amp;oldid=18645633</a> </div>")
			.append("<div id=catlinks class=catlinks data-mw=interface><div id=mw-normal-catlinks class=mw-normal-catlinks><a href=/wiki/%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%9A%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D1%96%D1%97 title=Спеціальна:Категорії>Категорії</a>: <ul><li><a href=/wiki/%D0%9A%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D1%96%D1%8F:%D0%9C%D0%BE%D0%B2%D0%BE%D0%B7%D0%BD%D0%B0%D0%B2%D1%81%D1%82%D0%B2%D0%BE title=Категорія:Мовознавство>Мовознавство</a></li><li><a href=/wiki/%D0%9A%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D1%96%D1%8F:%D0%A1%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D0%B8 title=Категорія:Символи>Символи</a></li><li><a href=/wiki/%D0%9A%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D1%96%D1%8F:%D0%9F%D0%B0%D0%BC%27%D1%8F%D1%82%D1%8C title=Категорія:Память>Память</a></li><li><a href=/wiki/%D0%9A%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D1%96%D1%8F:%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D0%B8_%D0%BD%D0%B0%D0%B2%D1%87%D0%B0%D0%BD%D0%BD%D1%8F title=Категорія:Методи навчання>Методи навчання</a></li><li><a href=/w/index.php?title=%D0%9A%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D1%96%D1%8F:%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=edit&amp;redlink=1 class=new title=Категорія:Мнемоніка (ще не написана)>Мнемоніка</a></li></ul></div></div> <div class=visualClear></div>")
			.append("</div>")
			.append("</div>")
			.append("<div id=mw-navigation>")
			.append("<h2>Навігаційне меню</h2>")
			.append("<div id=mw-head>")
			.append("<div id=p-personal role=navigation class= aria-labelledby=p-personal-label>")
			.append("<h3 id=p-personal-label>Особисті інструменти</h3>")
			.append("<ul>")
			.append("<li id=pt-anonuserpage>Ви не увійшли до системи</li><li id=pt-anontalk><a href=/wiki/%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%9C%D0%BE%D1%94_%D0%BE%D0%B1%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D0%B5%D0%BD%D0%BD%D1%8F title=Обговорення редагувань з цієї IP-адреси [n] accesskey=n>Обговорення</a></li><li id=pt-anoncontribs><a href=/wiki/%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%9C%D1%96%D0%B9_%D0%B2%D0%BD%D0%B5%D1%81%D0%BE%D0%BA title=Список редагувань, зроблених з цієї IP-адреси [y] accesskey=y>Внесок</a></li><li id=pt-createaccount><a href=/w/index.php?title=%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%A1%D1%82%D0%B2%D0%BE%D1%80%D0%B8%D1%82%D0%B8_%D0%BE%D0%B1%D0%BB%D1%96%D0%BA%D0%BE%D0%B2%D0%B8%D0%B9_%D0%B7%D0%B0%D0%BF%D0%B8%D1%81&amp;returnto=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0 title=Пропонуємо створити обліковий запис і увійти в систему; однак, це не обовязково>Створити обліковий запис</a></li><li id=pt-login><a href=/w/index.php?title=%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%92%D1%85%D1%96%D0%B4&amp;returnto=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0 title=Заохочуємо Вас увійти в систему, але це необовязково. [o] accesskey=o>Увійти</a></li> </ul>")
			.append("</div>")
			.append("<div id=left-navigation>")
			.append("<div id=p-namespaces role=navigation class=vectorTabs aria-labelledby=p-namespaces-label>")
			.append("<h3 id=p-namespaces-label>Простори назв</h3>")
			.append("<ul>")
			.append("<li id=ca-nstab-main class=selected><span><a href=/wiki/%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0 title=Вміст статті [c] accesskey=c>Стаття</a></span></li>")
			.append("<li id=ca-talk class=new><span><a href=/w/index.php?title=%D0%9E%D0%B1%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D0%B5%D0%BD%D0%BD%D1%8F:%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=edit&amp;redlink=1 title=Обговорення змісту сторінки [t] accesskey=t rel=discussion>Обговорення</a></span></li>")
			.append("</ul>")
			.append("</div>")
			.append("<div id=p-variants role=navigation class=vectorMenu emptyPortlet aria-labelledby=p-variants-label>")
			.append("<h3 id=p-variants-label>")
			.append("<span>Варіанти</span><a href=#></a>")
			.append("</h3>")
			.append("<div class=menu>")
			.append("<ul>")
			.append("</ul>")
			.append("</div>")
			.append("</div>")
			.append("</div>")
			.append("<div id=right-navigation>")
			.append("<div id=p-views role=navigation class=vectorTabs aria-labelledby=p-views-label>")
			.append("<h3 id=p-views-label>Перегляди</h3>")
			.append("<ul>")
			.append("<li id=ca-view class=collapsible><span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;stable=1 >Читати</a></span></li>")
			.append("<li id=ca-current class=collapsible collapsible selected><span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;stable=0&amp;redirect=no title=Переглянути цю сторінку з неперевіреними змінами [v] accesskey=v>Неперевірені зміни</a></span></li>")
			.append("<li id=ca-ve-edit><span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;veaction=edit title=Редагувати цю сторінку [v] accesskey=v>Редагувати</a></span></li>")
			.append("<li id=ca-edit class= collapsible><span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=edit title=Редагувати цю сторінку [e] accesskey=e>Редагувати код</a></span></li>")
			.append("<li id=ca-history class=collapsible><span><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=history title=Журнал змін сторінки [h] accesskey=h>Переглянути історію</a></span></li>")
			.append("</ul>")
			.append("</div>")
			.append("<div id=p-cactions role=navigation class=vectorMenu emptyPortlet aria-labelledby=p-cactions-label>")
			.append("<h3 id=p-cactions-label><span>Ще</span><a href=#></a></h3>")
			.append("<div class=menu>")
			.append("<ul>")
			.append("</ul>")
			.append("</div>")
			.append("</div>")
			.append("<div id=p-search role=search>")
			.append("<h3>")
			.append("<label for=searchInput>Пошук</label>")
			.append("</h3>")
			.append("<form action=/w/index.php id=searchform>")
			.append("<div id=simpleSearch>")
			.append("<input type=search name=search placeholder=Пошук у Вікіпедії title=Шукати у Вікіпедії [f] accesskey=f id=searchInput/><input type=hidden value=Спеціальна:Пошук name=title/><input type=submit name=fulltext value=Пошук title=Знайти сторінки, що містять зазначений текст id=mw-searchButton class=searchButton mw-fallbackSearchButton/><input type=submit name=go value=Перейти title=Перейти до сторінки, що має точно таку назву (якщо вона існує) id=searchButton class=searchButton/> </div>")
			.append("</form>")
			.append("</div>")
			.append("</div>")
			.append("</div>")
			.append("<div id=mw-panel>")
			.append("<div id=p-logo role=banner><a class=mw-wiki-logo href=/wiki/%D0%93%D0%BE%D0%BB%D0%BE%D0%B2%D0%BD%D0%B0_%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D0%BA%D0%B0 title=Перейти на головну сторінку></a></div>")
			.append("<div class=portal role=navigation id=p-navigation aria-labelledby=p-navigation-label>")
			.append("<h3 id=p-navigation-label>Навігація</h3>")
			.append("<div class=body>")
			.append("<ul>")
			.append("<li id=n-mainpage><a href=/wiki/%D0%93%D0%BE%D0%BB%D0%BE%D0%B2%D0%BD%D0%B0_%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D0%BA%D0%B0 title=Перейти на Головну сторінку [z] accesskey=z>Головна сторінка</a></li><li id=n-currentevents><a href=/wiki/%D0%92%D1%96%D0%BA%D1%96%D0%BF%D0%B5%D0%B4%D1%96%D1%8F:%D0%9F%D0%BE%D1%82%D0%BE%D1%87%D0%BD%D1%96_%D0%BF%D0%BE%D0%B4%D1%96%D1%97 title=Список поточних подій>Поточні події</a></li><li id=n-recentchanges><a href=/wiki/%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%9D%D0%BE%D0%B2%D1%96_%D1%80%D0%B5%D0%B4%D0%B0%D0%B3%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F title=Список останніх змін у цій вікі [r] accesskey=r>Нові редагування</a></li><li id=n-newpages><a href=/wiki/%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%9D%D0%BE%D0%B2%D1%96_%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D0%BA%D0%B8>Нові сторінки</a></li><li id=n-randompage><a href=/wiki/%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%92%D0%B8%D0%BF%D0%B0%D0%B4%D0%BA%D0%BE%D0%B2%D0%B0_%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D0%BA%D0%B0 title=Переглянути випадкову сторінку [x] accesskey=x>Випадкова стаття</a></li> </ul>")
			.append("</div>")
			.append("</div>")
			.append("<div class=portal role=navigation id=p-.D0.A3.D1.87.D0.B0.D1.81.D1.82.D1.8C aria-labelledby=p-.D0.A3.D1.87.D0.B0.D1.81.D1.82.D1.8C-label>")
			.append("<h3 id=p-.D0.A3.D1.87.D0.B0.D1.81.D1.82.D1.8C-label>Участь</h3>")
			.append("<div class=body>")
			.append("<ul>")
			.append("<li id=n-portal><a href=/wiki/%D0%92%D1%96%D0%BA%D1%96%D0%BF%D0%B5%D0%B4%D1%96%D1%8F:%D0%9F%D0%BE%D1%80%D1%82%D0%B0%D0%BB_%D1%81%D0%BF%D1%96%D0%BB%D1%8C%D0%BD%D0%BE%D1%82%D0%B8 title=Про проект, про те, що Ви можете зробити, і що де шукати>Портал спільноти</a></li><li id=n-tavern><a href=/wiki/%D0%92%D1%96%D0%BA%D1%96%D0%BF%D0%B5%D0%B4%D1%96%D1%8F:%D0%9A%D0%BD%D0%B0%D0%B9%D0%BF%D0%B0 title=Місце для обговорення більшості питань>Кнайпа</a></li><li id=n-help><a href=/wiki/%D0%92%D1%96%D0%BA%D1%96%D0%BF%D0%B5%D0%B4%D1%96%D1%8F:%D0%94%D0%BE%D0%B2%D1%96%D0%B4%D0%BA%D0%B0 title=Довідка з проекту>Довідка</a></li><li id=n-sitesupport><a href=//donate.wikimedia.org/wiki/Special:FundraiserRedirector?utm_source=donate&amp;utm_medium=sidebar&amp;utm_campaign=C13_uk.wikipedia.org&amp;uselang=uk title=Підтримайте проект>Пожертвування</a></li> </ul>")
			.append("</div>")
			.append("</div>")
			.append("<div class=portal role=navigation id=p-tb aria-labelledby=p-tb-label>")
			.append("<h3 id=p-tb-label>Інструменти</h3>")
			.append("<div class=body>")
			.append("<ul>")
			.append("<li id=t-whatlinkshere><a href=/wiki/%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%9F%D0%BE%D1%81%D0%B8%D0%BB%D0%B0%D0%BD%D0%BD%D1%8F_%D1%81%D1%8E%D0%B4%D0%B8/%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0 title=Перелік усіх сторінок, які посилаються на цю сторінку [j] accesskey=j>Посилання сюди</a></li><li id=t-recentchangeslinked><a href=/wiki/%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%9F%D0%BE%D0%B2%27%D1%8F%D0%B7%D0%B0%D0%BD%D1%96_%D1%80%D0%B5%D0%B4%D0%B0%D0%B3%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F/%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0 rel=nofollow title=Останні зміни на сторінках, на які посилається ця сторінка [k] accesskey=k>Повязані редагування</a></li><li id=t-specialpages><a href=/wiki/%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D1%96_%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D0%BA%D0%B8 title=Перелік спеціальних сторінок [q] accesskey=q>Спеціальні сторінки</a></li><li id=t-permalink><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;oldid=18645633 title=Постійне посилання на цю версію сторінки>Постійне посилання</a></li><li id=t-info><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;action=info title=Додаткові відомості про цю сторінку>Інформація про сторінку</a></li><li id=t-wikibase><a href=https://www.wikidata.org/wiki/Q191062 title=Посилання на пов’язаний елемент сховища даних [g] accesskey=g>Елемент Вікіданих</a></li><li id=t-cite><a href=/w/index.php?title=%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%A6%D0%B8%D1%82%D0%B0%D1%82%D0%B0&amp;page=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;id=18645633 title=Інформація про те, як цитувати цю сторінку>Цитувати сторінку</a></li> </ul>")
			.append("</div>")
			.append("</div>")
			.append("<div class=portal role=navigation id=p-coll-print_export aria-labelledby=p-coll-print_export-label>")
			.append("<h3 id=p-coll-print_export-label>Друк/експорт</h3>")
			.append("<div class=body>")
			.append("<ul>")
			.append("<li id=coll-create_a_book><a href=/w/index.php?title=%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%9A%D0%BD%D0%B8%D0%B3%D0%B0&amp;bookcmd=book_creator&amp;referer=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0>Створення книги</a></li><li id=coll-download-as-rdf2latex><a href=/w/index.php?title=%D0%A1%D0%BF%D0%B5%D1%86%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0:%D0%9A%D0%BD%D0%B8%D0%B3%D0%B0&amp;bookcmd=render_article&amp;arttitle=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;returnto=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;oldid=18645633&amp;writer=rdf2latex>Завантажити як PDF</a></li><li id=t-print><a href=/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;printable=yes title=Версія цієї сторінки для друку [p] accesskey=p>Версія до друку</a></li> </ul>")
			.append("</div>")
			.append("</div>")
			.append("<div class=portal role=navigation id=p-wikibase-otherprojects aria-labelledby=p-wikibase-otherprojects-label>")
			.append("<h3 id=p-wikibase-otherprojects-label>В інших проектах</h3>")
			.append("<div class=body>")
			.append("<ul>")
			.append("<li class=wb-otherproject-link wb-otherproject-commons><a href=https://commons.wikimedia.org/wiki/Category:Mnemonic hreflang=en>Вікісховище</a></li> </ul>")
			.append("</div>")
			.append("</div>")
			.append("<div class=portal role=navigation id=p-lang aria-labelledby=p-lang-label>")
			.append("<h3 id=p-lang-label>Іншими мовами</h3>")
			.append("<div class=body>")
			.append("<ul>")
			.append("<li class=interlanguage-link interwiki-af><a href=https://af.wikipedia.org/wiki/Eselsbrug title=Eselsbrug — африкаанс lang=af hreflang=af class=interlanguage-link-target>Afrikaans</a></li><li class=interlanguage-link interwiki-ar><a href=https://ar.wikipedia.org/wiki/%D8%A7%D8%B3%D8%AA%D8%B0%D9%83%D8%A7%D8%B1 title=استذكار — арабська lang=ar hreflang=ar class=interlanguage-link-target>العربية</a></li><li class=interlanguage-link interwiki-bg><a href=https://bg.wikipedia.org/wiki/%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D0%B8%D0%BA%D0%B0 title=Мнемоника — болгарська lang=bg hreflang=bg class=interlanguage-link-target>Български</a></li><li class=interlanguage-link interwiki-bn><a href=https://bn.wikipedia.org/wiki/%E0%A6%B8%E0%A7%8D%E0%A6%AE%E0%A7%83%E0%A6%A4%E0%A6%BF%E0%A6%AC%E0%A6%B0%E0%A7%8D%E0%A6%A7%E0%A6%A8%E0%A6%AC%E0%A6%BF%E0%A6%A6%E0%A7%8D%E0%A6%AF%E0%A6%BE title=স্মৃতিবর্ধনবিদ্যা — бенгальська lang=bn hreflang=bn class=interlanguage-link-target>বাংলা</a></li><li class=interlanguage-link interwiki-cs><a href=https://cs.wikipedia.org/wiki/Mnemotechnick%C3%A1_pom%C5%AFcka title=Mnemotechnická pomůcka — чеська lang=cs hreflang=cs class=interlanguage-link-target>Čeština</a></li><li class=interlanguage-link interwiki-cy><a href=https://cy.wikipedia.org/wiki/Cofair title=Cofair — валлійська lang=cy hreflang=cy class=interlanguage-link-target>Cymraeg</a></li><li class=interlanguage-link interwiki-de><a href=https://de.wikipedia.org/wiki/Merkspruch title=Merkspruch — німецька lang=de hreflang=de class=interlanguage-link-target>Deutsch</a></li><li class=interlanguage-link interwiki-el><a href=https://el.wikipedia.org/wiki/%CE%9C%CE%BD%CE%B7%CE%BC%CE%BF%CE%BD%CE%B9%CE%BA%CF%8C%CF%82_%CE%BA%CE%B1%CE%BD%CF%8C%CE%BD%CE%B1%CF%82 title=Μνημονικός κανόνας — грецька lang=el hreflang=el class=interlanguage-link-target>Ελληνικά</a></li><li class=interlanguage-link interwiki-en><a href=https://en.wikipedia.org/wiki/Mnemonic title=Mnemonic — англійська lang=en hreflang=en class=interlanguage-link-target>English</a></li><li class=interlanguage-link interwiki-eo><a href=https://eo.wikipedia.org/wiki/Memorhelpilo title=Memorhelpilo — есперанто lang=eo hreflang=eo class=interlanguage-link-target>Esperanto</a></li><li class=interlanguage-link interwiki-es><a href=https://es.wikipedia.org/wiki/Regla_mnemot%C3%A9cnica title=Regla mnemotécnica — іспанська lang=es hreflang=es class=interlanguage-link-target>Español</a></li><li class=interlanguage-link interwiki-et><a href=https://et.wikipedia.org/wiki/Mnemoonika title=Mnemoonika — естонська lang=et hreflang=et class=interlanguage-link-target>Eesti</a></li><li class=interlanguage-link interwiki-fa><a href=https://fa.wikipedia.org/wiki/%DB%8C%D8%A7%D8%AF%DB%8C%D8%A7%D8%B1 title=یادیار — перська lang=fa hreflang=fa class=interlanguage-link-target>فارسی</a></li><li class=interlanguage-link interwiki-fi><a href=https://fi.wikipedia.org/wiki/Muistis%C3%A4%C3%A4nt%C3%B6 title=Muistisääntö — фінська lang=fi hreflang=fi class=interlanguage-link-target>Suomi</a></li><li class=interlanguage-link interwiki-fr><a href=https://fr.wikipedia.org/wiki/Mn%C3%A9monique title=Mnémonique — французька lang=fr hreflang=fr class=interlanguage-link-target>Français</a></li><li class=interlanguage-link interwiki-he><a href=https://he.wikipedia.org/wiki/%D7%9E%D7%A0%D7%9E%D7%95%D7%A0%D7%99%D7%A7%D7%94 title=מנמוניקה — іврит lang=he hreflang=he class=interlanguage-link-target>עברית</a></li><li class=interlanguage-link interwiki-hi><a href=https://hi.wikipedia.org/wiki/%E0%A4%A8%E0%A4%BF%E0%A4%AE%E0%A5%8B%E0%A4%A8%E0%A4%BF%E0%A4%95 title=निमोनिक — гінді lang=hi hreflang=hi class=interlanguage-link-target>हिन्दी</a></li><li class=interlanguage-link interwiki-hy><a href=https://hy.wikipedia.org/wiki/%D5%84%D5%B6%D5%A5%D5%B4%D5%B8%D5%B6%D5%AB%D5%AF%D5%A1 title=Մնեմոնիկա — вірменська lang=hy hreflang=hy class=interlanguage-link-target>Հայերեն</a></li><li class=interlanguage-link interwiki-id><a href=https://id.wikipedia.org/wiki/Jembatan_keledai title=Jembatan keledai — індонезійська lang=id hreflang=id class=interlanguage-link-target>Bahasa Indonesia</a></li><li class=interlanguage-link interwiki-ja><a href=https://ja.wikipedia.org/wiki/%E8%A8%98%E6%86%B6%E8%A1%93 title=記憶術 — японська lang=ja hreflang=ja class=interlanguage-link-target>日本語</a></li><li class=interlanguage-link interwiki-kk><a href=https://kk.wikipedia.org/wiki/%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D0%B8%D0%BA%D0%B0 title=Мнемоника — казахська lang=kk hreflang=kk class=interlanguage-link-target>Қазақша</a></li><li class=interlanguage-link interwiki-ko><a href=https://ko.wikipedia.org/wiki/%EA%B8%B0%EC%96%B5%EC%88%A0 title=기억술 — корейська lang=ko hreflang=ko class=interlanguage-link-target>한국어</a></li><li class=interlanguage-link interwiki-mk><a href=https://mk.wikipedia.org/wiki/%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D0%B8%D0%BA%D0%B0 title=Мнемоника — македонська lang=mk hreflang=mk class=interlanguage-link-target>Македонски</a></li><li class=interlanguage-link interwiki-nl><a href=https://nl.wikipedia.org/wiki/Ezelsbruggetje title=Ezelsbruggetje — голландська lang=nl hreflang=nl class=interlanguage-link-target>Nederlands</a></li><li class=interlanguage-link interwiki-pt><a href=https://pt.wikipedia.org/wiki/Mnem%C3%B3nica title=Mnemónica — португальська lang=pt hreflang=pt class=interlanguage-link-target>Português</a></li><li class=interlanguage-link interwiki-ru><a href=https://ru.wikipedia.org/wiki/%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D0%B8%D0%BA%D0%B0 title=Мнемоника — російська lang=ru hreflang=ru class=interlanguage-link-target>Русский</a></li><li class=interlanguage-link interwiki-simple><a href=https://simple.wikipedia.org/wiki/Mnemonic title=Mnemonic — Simple English lang=simple hreflang=simple class=interlanguage-link-target>Simple English</a></li><li class=interlanguage-link interwiki-sv><a href=https://sv.wikipedia.org/wiki/Minnesregel title=Minnesregel — шведська lang=sv hreflang=sv class=interlanguage-link-target>Svenska</a></li><li class=interlanguage-link interwiki-ta><a href=https://ta.wikipedia.org/wiki/%E0%AE%A8%E0%AE%BF%E0%AE%A9%E0%AF%88%E0%AE%B5%E0%AE%BF title=நினைவி — тамільська lang=ta hreflang=ta class=interlanguage-link-target>தமிழ்</a></li><li class=interlanguage-link interwiki-th><a href=https://th.wikipedia.org/wiki/%E0%B8%99%E0%B8%B5%E0%B9%82%E0%B8%A1%E0%B8%99%E0%B8%B4%E0%B8%84 title=นีโมนิค — тайська lang=th hreflang=th class=interlanguage-link-target>ไทย</a></li><li class=interlanguage-link interwiki-tr><a href=https://tr.wikipedia.org/wiki/Nimonik title=Nimonik — турецька lang=tr hreflang=tr class=interlanguage-link-target>Türkçe</a></li><li class=interlanguage-link interwiki-ur><a href=https://ur.wikipedia.org/wiki/%D9%81%D9%86_%D8%AD%D9%81%D8%B8 title=فن حفظ — урду lang=ur hreflang=ur class=interlanguage-link-target>اردو</a></li><li class=interlanguage-link interwiki-zh><a href=https://zh.wikipedia.org/wiki/%E8%AE%B0%E5%BF%86%E6%9C%AF title=记忆术 — китайська lang=zh hreflang=zh class=interlanguage-link-target>中文</a></li> </ul>")
			.append("<div class=after-portlet after-portlet-lang><span class=wb-langlinks-edit wb-langlinks-link><a href=https://www.wikidata.org/wiki/Q191062#sitelinks-wikipedia title=Редагувати міжмовні посилання class=wbc-editpage>Редагувати посилання</a></span></div> </div>")
			.append("</div>")
			.append("</div>")
			.append("</div>")
			.append("<div id=footer role=contentinfo>")
			.append("<ul id=footer-info>")
			.append("<li id=footer-info-lastmod> Цю сторінку востаннє змінено: 23:17, 16 серпня 2016.</li>")
			.append("<li id=footer-info-copyright>Текст доступний на умовах ліцензії <a href=https://creativecommons.org/licenses/by-sa/3.0/>Creative Commons Attribution-ShareAlike</a>;")
			.append("також можуть діяти додаткові умови.")
			.append("Детальніше див. <a href=https://wikimediafoundation.org/wiki/Умови_використання>Умови використання</a>.</li>")
			.append("</ul>")
			.append("<ul id=footer-places>")
			.append("<li id=footer-places-privacy><a href=https://wikimediafoundation.org/wiki/Privacy_policy class=extiw title=wmf:Privacy policy>Політика конфіденційності</a></li>")
			.append("<li id=footer-places-about><a href=/wiki/%D0%92%D1%96%D0%BA%D1%96%D0%BF%D0%B5%D0%B4%D1%96%D1%8F:%D0%9F%D1%80%D0%BE title=Вікіпедія:Про>Про Вікіпедію</a></li>")
			.append("<li id=footer-places-disclaimer><a href=/wiki/%D0%92%D1%96%D0%BA%D1%96%D0%BF%D0%B5%D0%B4%D1%96%D1%8F:%D0%92%D1%96%D0%B4%D0%BC%D0%BE%D0%B2%D0%B0_%D0%B2%D1%96%D0%B4_%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%96 title=Вікіпедія:Відмова від відповідальності>Відмова від відповідальності</a></li>")
			.append("<li id=footer-places-contact><a href=//uk.wikipedia.org/wiki/Вікіпедія:Зворотний_зв%27язок>Зворотний звязок</a></li>")
			.append("<li id=footer-places-developers><a href=https://www.mediawiki.org/wiki/Special:MyLanguage/How_to_contribute>Розробники</a></li>")
			.append("<li id=footer-places-cookiestatement><a href=https://wikimediafoundation.org/wiki/Cookie_statement>Куки</a></li>")
			.append("<li id=footer-places-mobileview><a href=//uk.m.wikipedia.org/w/index.php?title=%D0%9C%D0%BD%D0%B5%D0%BC%D0%BE%D0%BD%D1%96%D0%BA%D0%B0&amp;mobileaction=toggle_view_mobile class=noprint stopMobileRedirectToggle>Мобільний вигляд</a></li>")
			.append("</ul>")
			.append("<ul id=footer-icons class=noprint>")
			.append("<li id=footer-copyrightico>")
			.append("<a href=https://wikimediafoundation.org/><img src=/static/images/wikimedia-button.png srcset=/static/images/wikimedia-button-1.5x.png 1.5x, /static/images/wikimedia-button-2x.png 2x width=88 height=31 alt=Wikimedia Foundation/></a> </li>")
			.append("<li id=footer-poweredbyico>")
			.append("<a href=//www.mediawiki.org/><img src=/static/images/poweredby_mediawiki_88x31.png alt=Powered by MediaWiki srcset=/static/images/poweredby_mediawiki_132x47.png 1.5x, /static/images/poweredby_mediawiki_176x62.png 2x width=88 height=31/></a> </li>")
			.append("</ul>")
			.append("<div style=clear:both></div>")
			.append("</div>")
			.append("<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({wgBackendResponseTime:87,wgHostname:mw1186});});</script>")
			.append("</body>")
			.append("</html>")
			.toString();

}
